## DEPLOYMENT
name: frontend
replicas: 1
strategy: RollingUpdate
persistence:
  enabled: false
image:
  repository: 325503636955.dkr.ecr.us-east-2.amazonaws.com/repone-frontend-service
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ecr-pull-secret
port: 80
resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
probes:
  path: /
  liveness:
    initialDelaySeconds: 5
  readiness:
    initialDelaySeconds: 5
