apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-service-pvc
  namespace: repone
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
