apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AgustinLandriel/retail-inventory-gitops.git
    targetRevision: master
    path: apps/repone-chart
    helm:
      valueFiles:
        - values.yaml
        - values/auth-service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: repone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
